learn/urls.py
from django.urls import path

from . import views

app_name = 'learn'

urlpatterns = [
    path('wordbook/', views.wordbook, name='wordbook'),
    path('wordbook/wordbookunit', views.wordbookunit, name='wordbookunit'),
    path('wordbook/wordbookunit/wordlist', views.wordlist, name='wordlist'),
    path('wordbook/mine', views.mywordbook, name='mywordbook'),
    path('learnindex/', views.learnindex, name='learnindex'),
    path('bdcsetting/', views.bdcsetting, name='bdcsetting'),
    path('learnindex/learnwords', views.learnwords, name='learnwords'),
    path('handleselfword/', views.handleselfword, name='selfword'),
    path('mywords/', views.mywords, name='mywords'),
    path('voctest/', views.voctest, name='voctest'),
    path('logout/', views.logout_view, name='logout'),
]

learningsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('account/', include('account.urls', namespace='account')),
    path('learn/', include('learn.urls', namespace='learn')),
    path('admin/', admin.site.urls),
]

learn/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Word(models.Model):
    spelling = models.CharField(blank=False, max_length=100, verbose_name = u"拼写")
    meaning = models.CharField(blank=False, max_length=300, verbose_name=u"解释")
    mp3_url = models.URLField(blank=True, verbose_name="mp3")

    class Meta:
        verbose_name = u"单词"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return self.spelling


class WordBook(models.Model):
    title = models.CharField(blank=True, max_length=50,
                                   verbose_name=u"书名")
    description = models.CharField(blank=True, max_length=200,
                                   verbose_name=u"描述")
    uploaded_user = models.ForeignKey(User, verbose_name=u"上传人", on_delete=models.CASCADE)
    word_num = models.IntegerField(default=1000, verbose_name=u"单词数")

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return self.description

    class Meta:
        verbose_name = u"单词本"
        verbose_name_plural = verbose_name

class WordUnit(models.Model):
    book = models.ForeignKey(WordBook, verbose_name = u"单词本", on_delete=models.CASCADE)
    unit_order = models.IntegerField(default=1, verbose_name=u"顺序")
    word_num = models.IntegerField(default=2000, verbose_name=u"单词数")

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0} - unit {1}".format(self.book.title, self.unit_order)

    class Meta:
        verbose_name = u"单元"
        verbose_name_plural = verbose_name

class WordInUnit(models.Model):
    word = models.ForeignKey(Word, verbose_name = u"单词", on_delete=models.DO_NOTHING)
    wordunit = models.ForeignKey(WordUnit, verbose_name=u"单元", on_delete=models.CASCADE)
    word_order = models.IntegerField(default=1, verbose_name=u"顺序")

    class Meta:
        verbose_name = u"单元单词"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0} - unit {1}".format(self.word, self.wordunit)

class LearningPlan(models.Model):
    user = models.ForeignKey(User, verbose_name=u"用户", on_delete=models.CASCADE)
    wordbook = models.ForeignKey(WordBook, verbose_name=u"单词本", on_delete=models.CASCADE)

    class Meta:
        verbose_name = u"学习计划"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0} - {1}".format(self.user.username, self.wordbook)

class LearningRecord(models.Model):
    user = models.ForeignKey(User, verbose_name=u"用户", on_delete=models.CASCADE)
    wordbook = models.ForeignKey(WordBook, verbose_name=u"单词本", on_delete=models.CASCADE)    
    islearning = models.IntegerField(default=0, verbose_name=u"正在学习")
    learn_time = models.DateTimeField(default=datetime.now,
                                      verbose_name=u"学习时间")
    duration = models.IntegerField(default=0, verbose_name=u"学习时长")
    correct_rate = models.IntegerField(default=100, verbose_name=u"正确率")
    haslearned = models.IntegerField(default=0, verbose_name=u"已经学习")

    class Meta:
        verbose_name = u"学习记录"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0} - isornotlearning{1}".format(self.user.username, self.islearning)

class UserSetting(models.Model):
    user = models.ForeignKey(User, verbose_name=u"用户", on_delete=models.CASCADE)
    dailyword = models.IntegerField(default=50, verbose_name=u"每日学习量")
    showmeaning = models.IntegerField(default=1, verbose_name=u"英文解释")
    learntype = models.IntegerField(default=1, verbose_name=u"单词的目标掌握程度")

    class Meta:
        verbose_name = u"用户设置"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0} - {1}".format(self.user.username, self.dailyword)

class UserDefWords(models.Model):
    user = models.ForeignKey(User, verbose_name=u"用户", on_delete=models.CASCADE)
    word = models.ForeignKey(Word, verbose_name = u"单词", on_delete=models.DO_NOTHING)
    
    class Meta:
        verbose_name = u"用户自定义单词"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return u"{0} - {1}".format(self.user.username, self.word.spelling)

learn/views.py
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

from .models import *
from learn.constants import *

from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.urls import reverse
# Create your views here.

import datetime

try:
    from django.utils import simplejson as json
except ImportError:
    import json

class DateEncoder(json.JSONEncoder):  
    def default(self, obj):  
        if isinstance(obj, datetime.datetime):  
            return obj.strftime('%Y-%m-%d %H:%M:%S')  
        elif isinstance(obj, date):  
            return obj.strftime("%Y-%m-%d")  
        else:  
            return json.JSONEncoder.default(self, obj) 

def get_all_books():
    all_wordbooks = WordBook.objects.all()
    wordbook_info = []
    for wordbook in all_wordbooks:
        info = {}
        info['title'] = wordbook.title
        info['description'] = wordbook.description
        info['uploaded_user'] = wordbook.uploaded_user.username
        info['word_num'] = wordbook.word_num
        info['wordbook_id'] = wordbook.id
        wordbook_info.append(info)
    return wordbook_info

@login_required
def wordbook(request):
    user = request.user
    all_wordbooks = WordBook.objects.all()
    wordbook_info = []
    for wordbook in all_wordbooks:
        info = {}
        info['title'] = wordbook.title
        info['description'] = wordbook.description
        info['uploaded_user'] = wordbook.uploaded_user.username
        info['word_num'] = wordbook.word_num
        info['wordbook_id'] = wordbook.id
        wordbook_info.append(info)
        user_name = user.username
    return render(request, 'workbook.html', {'data': wordbook_info, 'username': user_name})

@login_required
def wordbookunit(request):
    passed = {}
    passed['wordbook_info'] = get_all_books()
    user = request.user
    if request.method == "GET":
        if 'id' in request.GET:
            all_words_num = 0
            wordbook_id = request.GET['id']
            get_book = WordBook.objects.get(id=wordbook_id)
            passed['title'] = get_book.title
            passed['description'] = get_book.description
            #passed['word_num'] = get_book.word_num
            passed['uploaded_user'] = get_book.uploaded_user.username
            passed['username'] = user.username
            wordbookunit = WordUnit.objects.filter(book=get_book)
            if LearningPlan.objects.filter(user=user, wordbook=get_book).count() > 0:
                passed['save_button_name'] = SAVE_BUTTON[1]
            else:
                passed['save_button_name'] = SAVE_BUTTON[0]
            wb_info = []
            for wb in wordbookunit:
                info = {}
                info['unit_name'] = 'unit' + str(wb.unit_order)
                info['word_num'] = wb.word_num
                info['unit_id'] = wb.id
                all_words_num += wb.word_num
                wb_info.append(info)
            passed['allunits'] = wb_info
            passed['word_num'] = all_words_num   
            passed['wordbook_id'] = wordbook_id
    if request.method == 'POST':
        value = request.POST.get('value', None)
        get_book = WordBook.objects.get(id=int(value))
        if LearningPlan.objects.filter(user=user, wordbook=get_book).count() > 0:
            LearningPlan.objects.get(user=user, wordbook=get_book).delete()
            lr = LearningRecord.objects.get(user=user, wordbook=get_book)
            lr.islearning = 0
            lr.save()
        else:
            lp = LearningPlan(user=user, wordbook=get_book)
            lp.save()
            if LearningRecord.objects.filter(user=user, wordbook=get_book).count() == 0:
                lr = LearningRecord(user=user, wordbook=get_book)
                if LearningRecord.objects.filter(user=user, islearning=1).count() == 0:
                    lr.islearning = 1
                lr.save()
            else:
                r = LearningRecord.objects.get(user=user, islearning=1)
                r.islearning = 0
                r.save()
                lr = LearningRecord.objects.get(user=user, wordbook=get_book)
                lr.islearning = 1
                lr.save()
        ctx = {'message': user.username}
        return HttpResponse(json.dumps(ctx), content_type='application/json')
        #plan = LearningPlan(user=get_book.uploaded_user,wordbook=get_book)
        #plan.save()
    return render(request, 'wordbookunit.html', passed)

@login_required
def wordlist(request):
    passed = {}
    user = request.user
    passed['wordbook_info'] = get_all_books()
    if request.method == "GET":
        if 'id' in request.GET:
            unit_id = request.GET['id']
            get_unit = WordUnit.objects.get(id=unit_id)
            get_book = get_unit.book
            passed['title'] = get_book.title
            passed['unit'] = 'unit' + str(get_unit.unit_order)
            passed['word_num'] = get_unit.word_num
            passed['uploaded_user'] = get_book.uploaded_user.username
            passed['username'] = user.username
            passed['wordbook_id'] = get_book.id
            all_words = WordInUnit.objects.filter(wordunit=get_unit)
            
            words_list = []
            for wordunit in all_words:
                word_info = {}
                word_info['spelling'] = wordunit.word.spelling
                word_info['mean'] = wordunit.word.meaning
                words_list.append(word_info)
            passed['all_words'] = words_list
    return render(request, 'wordlist.html', passed)


@login_required
def mywordbook(request):
    passed = {}
    user = request.user
    passed['username'] = user.username
    passed['wordbook_info'] = get_all_books()

    #pdb.set_trace()
    print(request.method)
    if request.method == 'POST' and request.is_ajax():
        learning_id = request.POST.get('learning_id', None)
        learning_book = WordBook.objects.get(id=int(learning_id))
        learningrecord = LearningRecord.objects.get(user=user, wordbook=learning_book)
        learningrecord.islearning = 0
        learningrecord.save()

        value = request.POST.get('value', None)
        get_book = WordBook.objects.get(id=int(value))
        changedrecord = LearningRecord.objects.get(user=user, wordbook=get_book)
        changedrecord.islearning = 1
        changedrecord.save()

    userplans = LearningPlan.objects.filter(user=user)
    plan_books = []
    for plan in userplans:
        record = LearningRecord.objects.get(user=user, wordbook=plan.wordbook)
        if record.islearning:
            passed['learningbook'] = plan.wordbook.title
            passed['learningbook_num'] = plan.wordbook.word_num
            passed['learningbook_rate'] = 0 if plan.wordbook.word_num == 0 else "%.3f" % (record.haslearned/plan.wordbook.word_num)
            passed['learning_book_time'] = record.learn_time
            passed['learning_book_score'] = "%.3f" % record.correct_rate
            passed['learningbook_id'] = plan.wordbook.id
            #continue
        info = {}
        info['title'] = plan.wordbook.title
        info['num'] = plan.wordbook.word_num
        if plan.wordbook.word_num == 0:
            info['rate'] = float(0)
        else:
            info['rate'] = "%.3f" % (record.haslearned/plan.wordbook.word_num)
        info['book_id'] = plan.wordbook.id
        plan_books.append(info)
    passed['plan_book'] = plan_books

    #pdb.set_trace()
    if request.method == "GET":
        return render(request, 'mywordbook.html', passed)
    else:
        return HttpResponse(json.dumps(passed, cls=DateEncoder), content_type='application/json')

@login_required
def learnindex(request):
    user = request.user
    passed = {}
    passed['username'] = user.username
    if LearningRecord.objects.filter(user=user, islearning=1).count() == 1:
        lr = LearningRecord.objects.get(user=user, islearning=1)
        learningbook = lr.wordbook
        
        passed['title'] = learningbook.title
        passed['description'] = learningbook.description
        passed['word_num'] = learningbook.word_num
        passed['uploaded_user'] = learningbook.uploaded_user
        
        setting = UserSetting.objects.get(user=user)
        passed['plan_num'] = setting.dailyword
        passed['learned_num'] = lr.haslearned

    return render(request, "learnindex.html", passed)

@login_required
def bdcsetting(request):
    user = request.user
    usersetting = UserSetting.objects.get(user=user)
    ctx = {}
    ctx['username'] = user.username
    ctx['dailyword_list'] = dailyword_list
    ctx['showmeaning_list'] = showmeaning_list
    ctx['learntype_list'] = learntype_list
    #if request.method == "GET":
    #    ctx['dailyword'] = usersetting.dailyword
    #    ctx['showmeaning'] = usersetting.showmeaning
    #    ctx['learntype'] = usersetting.learntype
        
    if request.method == 'POST':
        definition = request.POST.get('definition', None)
        target_level = request.POST.get('target_level', None)
        quota = request.POST.get('quota', None)
        usersetting.dailyword = int(quota)
        usersetting.showmeaning = int(definition)
        usersetting.learntype = int(target_level)
        usersetting.save()

    ctx['dailyword'] = usersetting.dailyword
    ctx['showmeaning'] = usersetting.showmeaning
    ctx['learntype'] = usersetting.learntype

    return render(request, "bdcsetting.html", ctx)

@login_required
def learnwords(request):
    user = request.user
    if request.method == 'POST' and request.is_ajax():
        lr = LearningRecord.objects.get(user=user, islearning=1)
        lr.haslearned += 1
        lr.save()
        return HttpResponse(json.dumps({}, cls=DateEncoder), content_type='application/json')
    ctx = {} 
    ctx['username'] = user.username
    if LearningRecord.objects.filter(user=user, islearning=1).count() != 1:

learn/templates/learnwords.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{{username}}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar.css'%}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js'%}"></script>
    <style>
        .borderless > thead > tr > th,
        .borderless > tbody > tr > th,
        .borderless > tfoot > tr > th,
        .borderless > thead > tr > td,
        .borderless > tbody > tr > td,
        .borderless > tfoot > tr > td {
            border-top: none;
        }
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learn:learnindex' %}">单词学习</a></li>
                <li><a href="{% url 'learn:mywordbook' %}">我的单词本</a></li>
                <li><a href="{% url 'learn:wordbook' %}">单词本</a></li>
                <li><a href="{% url 'learn:voctest' %}">单词考核</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <div class="btn-group">
              <button type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{username}} <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="{% url 'learn:mywordbook' %}">我的单词本</a></li>
                <li><a href="{% url 'learn:mywords' %}">自定义单词</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'learn:bdcsetting' %}">设置</a></li>
                <li><a href="{% url 'learn:logout' %}">退出</a></li>
              </ul>
            </div>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      

    </div> <!-- /container -->

    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-8">
              {% for d in data %}  
                  <div class="row">
                    <div class="col-sm-6 col-md-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <h3 class="panel-title">
                                {{bookname}}
                              </h3>
                            </div>
                            <div class="panel-body">
                              {{d.word1_name}}
                              <button class="btn btn-success pull-right disable" id="learn-button{{d.word1_id}}" value="{{d.word1_id}}">
                                学习
                              </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <h3 class="panel-title">
                                  {{bookname}}
                              </h3>
                            </div>
                            <div class="panel-body">
                                {{d.word2_name}}
                              <button class="btn btn-success pull-right disable" id="learn-button{{d.word1_id}}" value="{{d.word1_id}}">
                                学习
                              </button>
                            </div>
                        </div>
                    </div>
                    
                  </div>
                  <!-- /.row -->
              {% endfor %}
            </div>
            <div class="col-sm-4 col-md-4">
                <div class="page-header">
                    <h3>维护自定义单词</h3>
                </div>
                <span class="hide" id="current-category-id">30</span>
                <ul class="nav nav-tabs nav-stacked">
                    <li data="10"><a href="#">查看自定义单词</a></li>
                    <li data="10"><a href="#" data-toggle="modal" data-target="#exampleModal" data-whatever="NewWord">添加自定义单词</a></li>
                </ul>
            </div>
        </div>
            <hr>
            <!-- Footer -->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-center">Copyright &copy; Lucien Words</p>
                    </div>
                </div>
                <!-- /.row -->
            </footer>
        
        </div>
        <!-- /.container -->

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="exampleModalLabel">添加自定义单词</h4>
            </div>
            <div class="modal-body">
              <form>
                <div class="form-group">
                  <label for="recipient-name" class="control-label">Spelling:</label>
                  <input type="text" class="form-control" id="recipient-name">
                </div>
                <div class="form-group">
                  <label for="message-text" class="control-label">Meaning:</label>
                  <textarea class="form-control" id="message-text"></textarea>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="save-btn">Save</button>
            </div>
          </div>
        </div>        
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <script type="text/javascript">
      $('.disable').click(function(){
        $(this).prop('disabled', true);
      });
    </script>
    -->
    {% for d in data %}
    <script>
        $('#learn-button{{d.word1_id}}').click(function(){
              $.ajax({
                        type: "POST",
                        url: "{% url 'learn:learnwords' %}",
                        data: {'value': $('this').attr('value'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: "json",
                        success: function(response) {
                          $('.disable').click(function(){
                            $(this).prop('disabled', true);
                          });
                        },
                        error: function(rs, e) {
                               alert(rs.responseText);
                        }
                  }); 
            })
    </script>
    <script>
        $('#learn-button{{d.word2_id}}').click(function(){
              $.ajax({
                        type: "POST",
                        url: "{% url 'learn:learnwords' %}",
                        data: {'value': $(this).attr('value'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: "json",
                        success: function(response) {
                          $('.disable').click(function(){
                            $(this).prop('disabled', true);
                          });
                        },
                        error: function(rs, e) {
                               alert(rs.responseText);
                        }
                  }); 
            })
    </script>
    {% endfor %}
    <script>
        $(function() {
            $('#myModal{{book.book_id}}').modal('hide')
        });
    </script>
    <script>
        $('#exampleModal').on('show.bs.modal', function (event) {
          var button = $(event.relatedTarget) // Button that triggered the modal
          var recipient = button.data('whatever') // Extract info from data-* attributes
          // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
          // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
          var modal = $(this)
          modal.find('.modal-title').text('自定义单词：' + recipient)
          modal.find('.modal-body input').val(recipient)
        })
    </script>
    <script>
        $('#save-btn').click(function(){
              $.ajax({
                        type: "POST",
                        url: "{% url 'learn:selfword' %}",
                        data: {'name': $('#recipient-name').val(), 'mean': $('#message-text').val(), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: "json",
                        success: function(response) {
                          alert(response.msg);
                        },
                        error: function(rs, e) {
                            alert(rs.responseText);
                        }
                  }); 
            })
    </script>
  </body>
</html>

learn/templates/workbook.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{{username}}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar.css'%}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js'%}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learn:learnindex' %}">单词学习</a></li>
                <li><a href="{% url 'learn:mywordbook' %}">我的单词本</a></li>
                <li class="active"><a href="{% url 'learn:wordbook' %}">单词本</a></li>
                <li><a href="{% url 'learn:voctest' %}">单词考核</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <div class="btn-group">
              <button type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{username}} <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="{% url 'learn:mywordbook' %}">我的单词本</a></li>
                <li><a href="{% url 'learn:mywords' %}">自定义单词</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'learn:bdcsetting' %}">设置</a></li>
                <li><a href="{% url 'learn:logout' %}">退出</a></li>
              </ul>
            </div>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      {% for wordbook in data %}
      <div class="jumbotron">
        <h1>{{wordbook.title}}</h1>
        <p>{{wordbook.description}}</p>
        <p>
          <a class="btn btn-lg btn-primary" href="wordbookunit?id={{wordbook.wordbook_id}}" role="button">Read More &raquo;</a>
        </p>
      </div>
      {% endfor %}

    </div> <!-- /container -->
    <hr>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p class="text-center">Copyright &copy; Lucien Words</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>