account/urls.py
from django.urls import include, path

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('forgot/', views.forgot, name='forgot'),
    path('learn/', include('learn.urls')),
]

learn/urls.py
from django.urls import path

from . import views

app_name = 'learn'

urlpatterns = [
    path('wordbook/', views.wordbook, name='wordbook'),
    path('wordbook/wordbookunit', views.wordbookunit, name='wordbookunit'),
    path('wordbook/wordbookunit/wordlist', views.wordlist, name='wordlist'),
    path('wordbook/mine', views.mywordbook, name='mywordbook'),
    path('learnindex/', views.learnindex, name='learnindex'),
    path('bdcsetting/', views.bdcsetting, name='bdcsetting'),
    path('learnindex/learnwords', views.learnwords, name='learnwords'),
    path('handleselfword/', views.handleselfword, name='selfword'),
    path('mywords/', views.mywords, name='mywords'),
    path('voctest/', views.voctest, name='voctest'),
    path('logout/', views.logout_view, name='logout'),
]

learningsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('account/', include('account.urls', namespace='account')),
    path('learn/', include('learn.urls', namespace='learn')),
    path('admin/', admin.site.urls),
]

account/models.py
from django.db import models
from django.contrib.auth.hashers import make_password

# Create your models here.

# User model not used
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField()

    def __unicode__(self):
        return self.user

    def save(self,*args,**kwargs):
        self.password = make_password(self.password) 
        super(User,self).save(*args,**kwargs)

account/forms.py
from django import forms

class UserForm(forms.Form):
    name = forms.CharField(label='name',max_length=100)
    password = forms.CharField(label='password',min_length=6,widget=forms.PasswordInput())
    confirmedpassword = forms.CharField(label='confirmedpassword',min_length=6,widget=forms.PasswordInput())
    email = forms.EmailField(label='email')

class UserFormLogin(forms.Form):
    email = forms.EmailField(label='email')
    password = forms.CharField(label='password',min_length=6,widget=forms.PasswordInput())

account/views.py
from django.shortcuts import render, render_to_response, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import make_password, check_password

from learn.models import UserSetting

from .forms import UserForm, UserFormLogin
# import pdb

# Create your views here.
def index(request):
    return render(request, 'index.html')

def login(request):
    if request.method == "POST":
        form = UserFormLogin(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            userResult = User.objects.filter(email=email)
            if userResult:
                p = User.objects.get(email=email)
                ps_bool = check_password(password, p.password)
                #user = authenticate(request, email=email)
                if ps_bool:
                    auth.login(request, p)
                    request.session['username'] = p.username
                    return redirect('learn:mywordbook')
                else:
                    return render(request,'login.html',{"errors":"密码错误"})
            else:
                return render(request,'login.html',{"errors":"邮箱不存在"})
        else:
            return render(request,'login.html',{'errors': "请检查填写的内容！"})
    else:
        return render(request, 'login.html')

def register(request):
    message = "请检查填写的内容！注意邮箱格式和密码长度至少6位"
    #pdb.set_trace()
    if request.method == 'POST':
        #pdb.set_trace()
        form = UserForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')                        
            username = form.cleaned_data['name']
            filterResult = User.objects.filter(email = email)

            if len(filterResult)>0:
                return render(request,'register.html',{"errors":"邮箱已存在"})
            elif form.cleaned_data.get('password') != form.cleaned_data.get('confirmedpassword'):
                errors = []
                errors.append("两次输入的密码不一致!")
                return render(request,'register.html',{'errors':errors})
            password = form.cleaned_data.get('password')
            
            user = User(username=username,password=make_password(password),email=email)
            user.save()
            setting = UserSetting(user=user)
            setting.save()
            return render(request,'success.html',{'operation':"注册"})
        else:
            return render(request,'register.html',{'errors': message})
    else:
        return render(request, 'register.html')

def forgot(request):
    return render(request, 'forgot.html')

account/templates/forgot.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>My Login Page &mdash; Bootstrap 4 Login Page Snippet</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/my-login.css'%}">
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center align-items-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{%static 'img/logo.jpg'%}">
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Forgot Password</h4>
							<form method="POST">
							 
								<div class="form-group">
									<label for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
									<div class="form-text text-muted">
										By clicking "Reset Password" we will send a password reset link
									</div>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										Reset Password
									</button>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2018 &mdash; LucienXian
					</div>
				</div>
			</div>
		</div>
	</section>
</body>
</html>

account/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>My Login Page &mdash; Bootstrap 4 Login Page Snippet</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/my-login.css'%}">
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{%static 'img/logo.jpg'%}">
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Login</h4>
							<form method="POST">{% csrf_token %}
								{{errors}}
								<div class="form-group">
									<label for="email">E-Mail Address</label>

									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
								</div>

								<div class="form-group">
									<label for="password">Password
										<a href="{% url 'account:forgot'%}" class="float-right">
											Forgot Password?
										</a>
									</label>
									<input id="password" type="password" class="form-control" name="password" required data-eye>
								</div>

								<div class="form-group">
									<label>
										<input type="checkbox" name="remember"> Remember Me
									</label>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										Login
									</button>
								</div>
								<div class="margin-top20 text-center">
									Don't have an account? <a href="{% url 'account:register'%}">Create One</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2018 &mdash; LucienXian
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{%static 'js/jquery.min.js'%}"></script>
	<script src="{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
	<script src="{%static 'js/my-login.js'%}"></script>
</body>
</html>

account/templates/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>My Login Page &mdash; Bootstrap 4 Login Page Snippet</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/my-login.css'%}">
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{%static 'img/logo.jpg'%}">
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">Register</h4>
							<form method="POST"> {% csrf_token %}
								{{errors}}
								<div class="form-group">
									<label for="name">Name</label>
									<input id="name" type="text" class="form-control" name="name" required autofocus>
								</div>

								<div class="form-group">
									<label for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" required>
								</div>

								<div class="form-group">
									<label for="password">Password</label>
									<input id="password" type="password" class="form-control" name="password" required data-eye>
								</div>

								<div class="form-group">
									<label for="confirmedpassword">Confirmed Password</label>
									<input id="confirmedpassword" type="password" class="form-control" name="confirmedpassword" required data-eye>
								</div>

								<div class="form-group">
									<label>
										<input type="checkbox" name="aggree" value="1"> I agree to the Terms and Conditions
									</label>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										Register
									</button>
								</div>
								<div class="margin-top20 text-center">
									Already have an account? <a href="{% url 'account:login'%}">Login</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2018 &mdash; LucienXian
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{%static 'js/jquery.min.js'%}"></script>
	<script src="{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
	<script src="{%static 'js/my-login.js'%}"></script>
</body>
</html>

account/templates/success.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
    </head>
    <body>
        <form method = 'post'> {% csrf_token %}
            <h1>恭喜,{{operation}}成功！</h1>
            </br>
            <a href="{% url 'account:login'%}" target="_blank"> 前往登陆页面 </a>
            </br>
            <a href="{% url 'account:register'%}" target="_blank"> 前往注册页面 </a>
        </form>
    </body>
</html>